### ISSUE TITLE
Erro Cadastro de usuário

### ISSUE THREAD

**Issue by engeziellithon** [SharebookBR/frontend#38]
Teste realizado no http://stg.sharebook.com.br

Estória
https://trello.com/c/LfzgkXRE/6-1-eu-enquanto-rodrigo-walter-preciso-me-cadastrar-no-sistema-para-que-possa-participar

Erros 
Critério de não aceite
Linkedin não valida se esta enviando uma URL
Cep aceita 1 número
Senha é confirmação de senha não são iguais
Email - Mensagem de validação de e-mail inválido está em inglês e todas as outras validações estão em português.

**Comment by wantero** [comment]
Foram liberadas as seguintes correções no Frontend:
Validação de e-mail válido
Validação de confirmação de senha
Validação de URL válida do perfil de Linkedin
Validação de formato de telefone
Validação de formato de CEP

A validação de e-mail inválido em inglês está vindo do Backend. Agora com a validação no frontend não deve mais acontecer, porém é preciso corrigir no Backend para que fique no padrão.

**Comment by wantero** [comment]
Ambiente de STG atualizado para validação.
