### ISSUE TITLE
AJUSTES DETALHES DO LIVRO

### ISSUE THREAD

**Issue by raffacabofrio** [SharebookBR/frontend#62]
Teste realizado no http://dev.sharebook.com.br

Estória: https://trello.com/c/hPCFWFnu/30-5-eu-enquanto-walter-donat%C3%A1rio-preciso-selecionar-um-livro-de-forma-que-eu-entre-na-fila-para-doa%C3%A7%C3%A3o-do-mesmo

- colocar url bonita ( slug )
ANTES: http://dev.sharebook.com.br/book/details/379d6827-4e06-4a23-a618-e5540053baaa
DEPOIS: http://dev.sharebook.com.br/livros/programando-o-android

- colocar texto no lugar de campos desabilitados.

- quando não estiver logado ter um botão. "faça o login para solicitar esse livro."

- Trocar nome de campo.
ANTES: Doador paga pelo frete?
DEPOIS: Você pagaria o frete pra ganhar esse livro?

- Ter um tela de resultado. Similar quando o doador doa um livro. Com opções de ir pro painel ou pra home.

**Comment by wantero** [comment]
- colocar url bonita (slug) - OK
- colocar texto no lugar de campos desabilitados - OK
- quando não estiver logado ter um botão para login - OK e com parâmetro na rota para ao logar já ficar diretamente no livro que estava
- Trocar nome de campo: Conforme alinhado foi alterado para "Doador paga o frete?"
- Ter uma tela de resultado - Mantive somente opção de ir para home, visto que essa função não é acessada do painel.

**Comment by wantero** [comment]
Algumas pendências identificadas:

- Por algum motivo algum PR do backend não está mais deixando carregar os dados de livros quando não está logado;

- Precisa adicionar o objeto de freightOptions na model de book para ter acesso a descrição do mesmo ou criar um método getFreightOptionsById;
